PREFIX referendum:  <http://prasija1/resources/referendum/#>
PREFIX dbo:  <http://dbpedia.org/ontology/#>
PREFIX town:  <http://prasija1.cz/resources/town/#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

select * where {
   ?ref a referendum:Referendum ;
     town:name ?town .
   VALUES (?town) { ("City of London"^^<http://www.w3.org/2001/XMLSchema#string>) }
}
